title: 'Integrative Holistic Therapies: Ancient Wisdom and spiritual technology with Sudevi Kramer, M.A. LMT, E-RYT 500'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7378037553280592
  brandStrength: 0.6384679530747235
  rhythmicContrast: 0.8739618076942861
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  lightness: 0.6564699951559305
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: 'Satya Healing '
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6618887
layout_spectrum: 0.8709949
